### ISSUE TITLE
Provide a means for a custom site-name to appear at the top-left, something other than just "hoot". 

### ISSUE THREAD

**Issue by JobDestroyer** [ProjectHoot/Hoot#21]
Admins would likely want to be able to change this to match their site name.

**Comment by npmaile** [comment]
from the discord: currently the user would have to edit https://github.com/ProjectHoot/Hoot/blob/a971a3dc155e5ccd03be977ff05c79228deaeda1/src/App.vue#L8

**Comment by JobDestroyer** [comment]
see #26

**Comment by Twitch0125** [comment]
handled by #26
