### ISSUE TITLE
Too much space between post info text and "COMMENTS" button

### ISSUE THREAD

**Issue by properal-gb** [ProjectHoot/Hoot#39]
This is a lot of unused space between the post info text the show time poster and community and the "COMMENTS" button.

**Comment by properal-gb** [comment]
![image](https://user-images.githubusercontent.com/67848761/106980536-379de180-6715-11eb-9e9a-f10286cff16d.png)

**Comment by squash** [comment]
This entire layout has been updated which solves this issue.
