### ISSUE TITLE
User concern over JavaScript and cookies

### ISSUE THREAD

**Issue by properal-gb** [ProjectHoot/Hoot#41]
User input:
Hoot looks like a bad idea
- First, it asks for JavaScript, even for reading.
- Than it needs to download JavaScript from a third party.
- Third, it needs to install cookies.
At this point you might just mirror Gold and Black on Twitter and Facebook.

Source:
https://www.reddit.com/r/GoldandBlack/comments/mtkx0p/hoot_looks_like_a_bad_idea/

**Comment by squash** [comment]
Hoot uses a javascript framework (vue.js) along with a css/js ui toolkit (Vuetify), and it uses a cookie to store your session key if you're logged in. This is how the web functions, javascript and cookies aren't evil even if it is possible to abuse them. Ou code is open and you can clearly see how we use these things, no reason to invent FUD.
