### ISSUE TITLE
Default to dark mode, have the setting saved in the user account

### ISSUE THREAD

**Issue by JobDestroyer** [ProjectHoot/Hoot#65]
Dark mode should be default for unauthenticated users and new users. We should save preferences for dark vs light mode so it remembers when they log in.

**Comment by squash** [comment]
Would it make sense to instead use the OS dark mode setting? Browsers are exposing this these days.

**Comment by Twitch0125** [comment]
that pull request updates the logic to account for the OS settings.
As for "remembering" what the user selected, right now we use localStorage and cookies and is not tied to the user's account. We'd probably need an update to Lotide to support some kind of User Metadata
